### ISSUE TITLE
[Pipeline] Add Flow

### ISSUE THREAD

**Issue by wsguede** [BMBros/TriviaNative#4]
- [ ] add flow to project
- [ ] add flow to ci pipeline as parallel pipeline to test and eslint
- [ ] force flow across project?
  - Currently atom will only check flow on files with `@flow` during build time, we shouldnt allow accidental 'forgot'
    - Does [options / all](https://flow.org/en/docs/config/options/#toc-all-boolean) get checked by atom?
      - Yes
        ```
        [options]
        all = true
        ```
      - No -- should we just
      `flow check --all`
- [ ] [use this](https://github.com/gajus/eslint-plugin-flowtype) to enforce flow?

**Comment by sdg9** [comment]
Alternatively if we want we could try out typescript. I know typescript can be enforced and it would be a new learning. I have 0 issues with flow though as we already know it.
