### ISSUE TITLE
[Pipeline] Add Build

### ISSUE THREAD

**Issue by wsguede** [BMBros/TriviaNative#5]
- [ ] add 'build' to pipeline
  - Currently we lint and test (soon to add flow) but we dont actually try to bundle the js.

**Comment by sdg9** [comment]
@wsguede is goal to build stand alone Android and iOS apps, or have users download expo and then load our app from that container?

Honestly I think for MVP we should (1) figure out if web is viable. If background browsing is a must block MVP feature (I get it, it's a big deal) is there any way we can detect when dom is not actively being viewed and drive off that?  If that can be solved via web, is web sufficient?

If native is required we should determine (2) long term plan do standalone apps make sense?  For MVP we could put behind fabric.io and distribute outside of the app store (I think we can with iOS without paying the $$$).
